### ISSUE TITLE
Provide code coverage check

### ISSUE THREAD

**Issue by mssola** [openSUSE/portusctl#4]
Code coverage is an important metric that will allow us gain confidence over our test suite. I plan to merge the coverage from both unit tests and integration tests in the same way @cyphar did in [openSUSE/umoci](https://github.com/openSUSE/umoci).

**Comment by cyphar** [comment]
https://www.cyphar.com/blog/post/20170412-golang-integration-coverage explains in more detail how `umoci`'s test suite works.
